name: Simple Workflow

on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Step 1
        id: step1
        run: echo "hello"
      - name: Step 2
        id: step2
        run: echo "world"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Set environment variables from job1 outputs
        run: |
          echo "OUTPUT1=${{ needs.job1.outputs.output1 }}" >> $GITHUB_ENV
          echo "OUTPUT2=${{ needs.job1.outputs.output2 }}" >> $GITHUB_ENV
      - name: Print job outputs
        run: |
          echo $OUTPUT1 $OUTPUT2
