name: Example Workflow with Job Outputs and Error Handling

on:
  push:  # Trigger on push events

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map step outputs to job outputs
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "::set-output name=test::hello"
      - name: Step 2
        id: step2
        run: |
          echo "::set-output name=test::world"
        # Handle potential errors in step2 (optional)
        # Add checks or error redirection here

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Depends on successful completion of job1
    steps:
      - name: Set environment variables from job1 outputs
        env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "test"  
      - name: Print job outputs
        run: |
          echo "$OUTPUT1 $OUTPUT2"

      # Handle potential errors in job2 (optional)
      # Add checks or error redirection here
