name: Example Workflow with Environment Files

on: [push]  # Trigger on push events

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - name: Generate some data
        run: echo "This is some data: value1=hello,value2=world" > data.env  # Create an environment file

  # Upload the environment file as an artifact for later access
  upload-data:
    runs-on: ubuntu-latest
    needs: generate-data  # This job depends on the generate-data job
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: data   # Name of the artifact
          path: data.env  # Path to the environment file

  # Download and use the data in another job
  use-data:
    runs-on: ubuntu-latest
    needs: upload-data  # This job depends on the upload-data job
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - uses: actions/download-artifact@v3
        with:
          name: data  # Name of the artifact (matches upload)
      - name: Print downloaded data
        run: cat data.env
